#! /bin/sh
setxkbmap us &
xsetroot -cursor_name left_ptr

# Start Program
pgrep -x sxhkd > /dev/null || sxhkd &
betterlockscreen -l
$HOME/.config/scripts/display.sh
$HOME/.config/scripts/polybar-launch.sh
picom -f &
nitrogen --restore &
fcitx5 -d &
antidot init &

#bspc monitor DP-2 -d Media Docs
#bspc monitor DP-4 -d Main Web
#bspc monitor HDMI-0 -d Chat Dev Extra Tools
bspc monitor -d Main Web Docs Tools Media Chat

# Handle Monitors
bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true

bspc config border_width 2
bspc config window_gap 16

bspc config normal_border_color "#4c566a"
bspc config focused_border_color "#88c0d0"

bspc config split_ratio         	0.5
bspc config borderless_monocle  	true
bspc config gapless_monocle     	true
bspc config focus_by_distance   	true
bspc config focus_follows_pointer	true
bspc config history_aware_focus     true
bspc config pointer_motion_interval 7ms

# Reset Rules
bspc rule -r *

# States
bspc rule -a '*:feh' state=floating
bspc rule -a '*:mpv' state=floating
bspc rule -a '*:Minecraft' state=floating
bspc rule -a zoom state=floating center=on follow=on
bspc rule -a discord desktop="Chat"
